name: specsuite_env_test
channels:
  - defaults
dependencies:
  - python>=3.0
  - pip
  - pip:
      - astropy>=7.0
      - ipywidgets>=8.0
      - joblib>=1.0
      - matplotlib>=3.0
      - numpy>=2.0
      - pandas>=2.0
      - requests>=2.0
      - scipy>=1.0
      - tqdm>=4.0
